version: '3'

services:
  producer:
    build: ./producer/.
    container_name: producer
    volumes:
      - ./data:/app/data:rw

  consumer:
    image: python:3.7-alpine
    container_name: consumer
    volumes:
      - ./data:/app/data:rw