version: '3'

services:
  producer:
    build: ./producer/.
    container_name: producer
    depends_on:
      - consumer
    volumes:
      - ./data:/app/data:rw

  consumer:
    build: ./consumer/.
    container_name: consumer
    volumes:
      - ./data:/app/data:rw